require('pry-byebug')
require_relative('../models/member')
require_relative('../models/gymclass')
require_relative('../models/booking')

member1 = Member.new({'first_name' => 'Kaspars', 'last_name' => 'Dzerins', 'membership_type' => "basic"})
member1.save()
member2 = Member.new({'first_name' => 'Tanny', 'last_name' => 'Qureshi', 'membership_type' => "basic"})
member2.save()
member3 = Member.new({'first_name' => 'Christian', 'last_name' => 'Geib', 'membership_type' => "basic"})
member3.save()
member4 = Member.new({'first_name' => 'Jane', 'last_name' => 'Duncan', 'membership_type' => "premium"})
member4.save()
member5 = Member.new({'first_name' => 'Connie', 'last_name' => 'Leighton', 'membership_type' => "premium"})
member5.save()

gymclass1 = GymClass.new({'name' => 'Yoga', 'instructor' => 'Bikram Choudhury', 'description' => 'By perverts, for perverts.', 'capacity' => 20})
gymclass1.save()
gymclass2 = GymClass.new({'name' => 'Lifting 101', 'instructor' => 'Rainier Luftwaffe Wolfcastle', 'description' => 'Come with me if you wanna lift!', 'capacity' => 3})
gymclass2.save()
gymclass3 = GymClass.new({'name' => 'Spinning for beginners', 'instructor' => 'Lance Liestrong', 'description' => 'All the sweat minus the distance.', 'capacity' => 20})
gymclass3.save()
gymclass4 = GymClass.new({'name' => 'Boxercise', 'instructor' => 'George Grillman', 'description' => 'For when you want to look tough without the risk of being punched in the face.', 'capacity' => 20})
gymclass4.save()

booking1 = Booking.new({'start_time' => "10:00:00", 'gym_class_id' => gymclass1.id, 'member_id' => member1.id})
booking1.save()
booking2 = Booking.new({'start_time' => "11:00:00", 'gym_class_id' => gymclass2.id, 'member_id' => member2.id})
booking2.save()
booking3 = Booking.new({'start_time' => "15:00:00", 'gym_class_id' => gymclass4.id, 'member_id' => member3.id})
booking3.save()
booking4 = Booking.new({'start_time' => "15:00:00", 'gym_class_id' => gymclass4.id, 'member_id' => member1.id})
booking4.save()

binding.pry
nil
